# Generated by Django 5.2.7 on 2025-10-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_desktop',
            field=models.ImageField(blank=True, null=True, upload_to='products/desktop/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='products/mobile/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_tablet',
            field=models.ImageField(blank=True, null=True, upload_to='products/tablet/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='products/thumbnails/'),
        ),
    ]
